<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Cms\Block\Widget\Block */

?>
<div class="widget block block-static-block">
    <?= /* @noEscape */ $block->getText() ?>
</div>

<!-- rodar slick -->
<script>
    require([
        'jquery',
        'slick'
    ], function($) {
        $(function() {
            $('.carousel-top').not('.slick-initialized').slick({
                dots: false,
                infinite: true,
                slidesToShow: 1,
                arrows: true,
                autoplay: true,
                autoplaySpeed: 2000,
            });
        });
    });
</script>
